steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t',
      'asia-northeast1-docker.pkg.dev/$PROJECT_ID/rss-batch/rss-batch:$COMMIT_SHA',
      '-t',
      'asia-northeast1-docker.pkg.dev/$PROJECT_ID/rss-batch/rss-batch:latest',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/rss-batch/rss-batch:$COMMIT_SHA'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/rss-batch/rss-batch:latest'
    ]

images:
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/rss-batch/rss-batch:$COMMIT_SHA'
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/rss-batch/rss-batch:latest'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
